# Generated by Django 5.0.6 on 2024-08-20 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
        ('peoples', '0002_alter_employee_salary'),
        ('products', '0002_alter_brand_owner_alter_category_owner_unit_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quentity', models.IntegerField()),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('payable', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('due', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='owners.owner')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='peoples.supplier')),
            ],
        ),
    ]
