# Generated by Django 5.0.6 on 2024-08-20 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
        ('peoples', '0002_alter_employee_salary'),
        ('products', '0002_alter_brand_owner_alter_category_owner_unit_product'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quentity', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('receivable', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('due', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=15)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='peoples.customer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='owners.owner')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='products.product')),
            ],
        ),
    ]
