# Generated by Django 5.0.6 on 2024-08-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='quentity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quentity',
            field=models.IntegerField(default=0),
        ),
    ]
