# Generated by Django 5.0.6 on 2024-10-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_alter_purchase_quentity_alter_sale_quentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='isPayment',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='isPayment',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
