# Generated by Django 5.0.6 on 2024-08-21 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_alter_owner_address'),
        ('peoples', '0007_alter_customer_address_alter_employee_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salarys', to='owners.owner'),
        ),
    ]
