# Generated by Django 5.0.6 on 2024-08-20 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_brand_owner_alter_category_owner_unit_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase', models.IntegerField()),
                ('sold', models.IntegerField()),
                ('available_stock', models.IntegerField()),
                ('sell_value', models.IntegerField()),
                ('purchase_value', models.IntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
