# Generated by Django 5.0.6 on 2024-08-20 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_alter_owner_address'),
        ('stocks', '0002_alter_stock_available_stock_alter_stock_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='owners.owner'),
        ),
    ]
